nam:
  dropout: 0
  n_basis_functions: 1000
  feature_dropout: 0
  shallow_layer: relu
  hidden_layer: relu
  units_multiplier: 64

train_params:
  seed: 11
  epochs: 10
  step_size: 5
  batch_size: 512

optimizer:
  lr: 0.001